/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg;

import static java.lang.Thread.sleep;
import java.util.Random;
import org.jcsp.lang.Any2OneChannel;
import org.jcsp.lang.Channel;
import org.jcsp.lang.One2OneChannel;
import org.jcsp.util.Buffer;

/**
 *
 * @author Pablo Pérez Muñoz
 */
public class Generador extends javax.swing.JFrame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        Random r = new Random();
        int random, tiempo, max = 30;
        
        Thread[] h = new Thread[max];
        
        Any2OneChannel entraC = Channel.any2one(new Buffer(max));
        Any2OneChannel entraE = Channel.any2one(new Buffer(max));
        Any2OneChannel entraF = Channel.any2one(new Buffer(max));
        Any2OneChannel saleC = Channel.any2one(new Buffer(max));
        Any2OneChannel sale = Channel.any2one(new Buffer(max));
        One2OneChannel permiso[] = Channel.one2oneArray(max, new Buffer(1));
        One2OneChannel salir = Channel.one2one(new Buffer(1));
        
        Controlador c = new Controlador(entraC.in(), entraE.in(), entraF.in(), saleC.in(), sale.in(), permiso, salir.in());
        c.start();
        

        try {
            System.out.println("EMPIEZA EL PROGRAMA");
            for (int i = 0; i < max; i++) {
                tiempo = r.nextInt(2) + 1;
                random = r.nextInt(100);
                sleep(tiempo * 1000);

                if (random < 50) {
                    h[i] = new Electrico(i, entraE.out(), permiso[i].in(), sale.out());
                } else if (random < 90) {
                    h[i] = new Thread(new Combustion(i, entraC.out(), permiso[i].in(), saleC.out()));
                } else {
                    h[i] = new Furgoneta(i, entraF.out(), permiso[i].in(), sale.out());
                }

                h[i].start();
            }

            System.out.println("TODOS LOS HILOS CREADOS");

            for (int i = 0; i < max; i++) {
                h[i].join();
            }
            
            salir.out().write(1);
            c.join();
            

        } catch (InterruptedException ex) {
            System.out.println(ex.getMessage());
        }

        System.out.println("FIN DEL PROGRAMA");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
